### ISSUE TITLE
neu ausgewerteten Farbvorschlag über dem Vorherigen 

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#11]
aktuell werden die neuennVorschläge unter dem vorherigen angehängt. Beim normalen spiel arbeitet man sich zum Mastercode hoch. Eventuell wäre auch eine kurzzeitige Hervorhebung des aktuellen Vorschlags Sinnvoll.

**Comment by hphilipp** [comment]
Neue Vorschläge werden jetzt oben eingesetzt. Außerdem hat jede Reihe nun eine Nummer, sodass die zuletzt benutzte sichtbar wird.
