### ISSUE TITLE
Spiel Auflösen ohne Abfrage

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#12]
Das Spiel wird sofort aufgelöst, wenn man auf den entsprechenden Knopf drückt. Eine Abfrage wäre hier nett, da man beim Eintragen eines Farbvorschlags gerne mal auf diesen Knopf kommt.

**Comment by maexbower** [comment]
Ebenso ist mir aufgefallen, dass wenn man während des Spiels auf die zurück Taste des Handys kommt man ebenfalls ohne Rückfrage aus dem laufenden Spiel geworfen wird (erhöht den "grrrrrrrrrr" Faktor beim Testen)

**Comment by hphilipp** [comment]
Beides jetzt implementiert. Braucht es das "Du hast das Spiel aufgelöst"- PopUp noch oder soll direkt nach der Bestätigung aufgelöst werden?

**Comment by Philhil** [comment]
Ich habe nun das zweite PopUp entfern.
