### ISSUE TITLE
UseCase #3 Öffnen der Einstellungen

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#14]
Nr. 3
Titel Öffnen der Einstellungen
Kurzbeschreibung Der Benutzer hat die Ansicht der Einstellungen geöffnet um die Parameter:
 1. Größe des Spielfelds
 2. Ändern des Aussehens
 3. Anpassen der Spielregeln

Akteure Benutzer
Auslösendes Ereignis Klick auf Einstellungssymbol im Hauptmenü
Vorbedingungen Kein laufendes Spiel
Nachbedingungen Keine
Perfomanceklasse 1
Priorisierung 3
Ablauf Benutzer ist im Hauptmenü. Benutzer klickt auf Einstellungssymbol. Anzeigen der aktuellen und möglichen Parameter.

**Comment by Philhil** [comment]
8ab1cabe2566bd7337c1be217d12be8e96a03c3f
