### ISSUE TITLE
UseCase #4 Speichern der Einstellungen

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#15]
Nr. 4
Titel Speichern der Einstellungen
Kurzbeschreibung Speichern der gesetzten Einstellungen
Akteure Benutzer
Auslösendes Ereignis Der Benutzer klickt auf die Speichern Schaltfläche in der
Einstellungsansicht
Vorbedingungen Einstellungsansicht wurde geöffnet
Nachbedingungen Keine
Perfomanceklasse 2
Priorisierung 3
Ablauf Benutzer drückt auf die Speichern Schaltfläche in der Optionsansicht. Die App speichert die gesetzten Parameter und Ändert die Einstellungen in der Laufzeit. Nach erfolgreichem Speichern wird das Hauptmenü gezeigt.

**Comment by hphilipp** [comment]
Die Einstellungen werden direkt gespeichert, sobald eine Änderung vorgenommen wird. Das nächste neue Spiel startet dann mit diesen Einstellungen.
Farbauswahl (also welche Farben auswählbar sein sollen) in den Einstellungen funktioniert noch nicht.

**Comment by maexbower** [comment]
Einstellung zur Hintergrundfarbe wird ebenfalls noch nicht benutzt.
Es gibt zwei Eingabefelder für die Anzahl der Farben. Einmal die Auswahl der Anzahl der Farben im Spiel und einmal die verschienden Farben gleich darunter. Entweder nur eins oder man beschränkt die Anzahl der möglichen Häkchen bei der Farbauswahl auf die Anzahl die darüber eingestellt wurde.
Mehrfachnutzung einer Farbe auch ohne Haken in der entsprechenden Einstellung möglich
