### ISSUE TITLE
UseCase #17 Anzeigen der Highscoreliste

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#20]
Nr. 17
Titel Anzeigen der Highscoreliste
Kurzbeschreibung Anzeigen der aktuellen Highscore Liste
Akteure Benutzer
Auslösendes Ereignis Betätigung der Schaltfläche „Highscoreliste anzeigen“
im Hauptmenü
Vorbedingungen App gestartet
Nachbedingungen Keine
Perfomanceklasse 2
Priorisierung 3
Ablauf Benutzer klickt auf die Schaltfläche „Highscoreliste anzeigen“ im Hauptmenü. App zeigt Highscoreliste an.

**Comment by maexbower** [comment]
Eventuell würde sich eine optische Trennung der Highscorelisten Zeilen gut machen. Ich kann mir da einen leichten grauen Strich, der nicht bis ganz zu den Seiten geht vorstellen.

**Comment by hphilipp** [comment]
Bei langen Spielernamen werden nicht alle Attribute (Felder, Farben, usw.) angezeigt.
