### ISSUE TITLE
UseCase #18 App beenden

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#21]
Nr. 18
Titel App beenden
Kurzbeschreibung Die App beendet sich.
Akteure Benutzer
Auslösendes Ereignis Betätigen der „zurück“ Taste des Smartphones im Hauptmenü. Benutzer bestätigt beenden der App.
Vorbedingungen App gestartet. Hauptmenü angezeigt
Nachbedingungen App beendet
Perfomanceklasse 3
Priorisierung 3
Ablauf Benutzer betätigt die „zurück“ Taste an seinem Smartphone. Die App zeigt die Abfrage ob der Benutzer die App schließen möchte. Bestätigt der Benutzer beendet sich die App.

**Comment by hphilipp** [comment]
Abfrage ist da und App wird beendet. Ist bei mir aber nicht in der Übersicht der Apps, die im Hintergrund geöffnet sind.

**Comment by maexbower** [comment]
Genau so habe ich mir das vorgestellt. Hierbei geht es weniger um den Energie- / Ressourcenverbrauch, sondern eher darum, dem User die Möglichkeit zu geben über den gewohnten Weg zu gehen (Zurück Taste führt mich irgendwann wieder ganz zurück). Mit der Abfrage wird verhindert, dass der Benuter durch ein ungwolltes drücken der Zurück Taste die App verlässt und bei einem alten Handy somit eine längere Wartezeit bis das Spiel wieder da ist verursacht.
