### ISSUE TITLE
Ergebis Anzeige für ausenstehende nicht sofort ersichtlich

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#23]
Grau ist erst von Schwarz unterscheidbar wenn beides einmal vorgekommen ist. Entweder deutlicher gesetzte und nicht gesetzte Pins hervorheben oder die freien leeren Vorschlagsreihen schon von Anfang an anzeigen.

**Comment by hphilipp** [comment]
Graue Pins haben eine neue Farbe erhalten (weißer Hintergrund mit grauen Pünktchen). Sie sind jetzt aber standardmäßig nicht mehr sichtbar.
-> sind nur noch drin, damit die Zentrierung der Reihe bei unterschiedlicher Anzahl Pins gleich bleibt.
