### ISSUE TITLE
Farbauswahl ergonomischer gestalten

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#27]
Kann die Farbauswahl eventuell etwas ergonomischer gestaltet werden?
Als Beispiel sei hier der Timepicker in der Android Uhr genannt.
Eine einfache Umsetzung wäre eventuell, wenn man auf das zu füllende Feld drückt und dann auf Ebene der Eingabefelder mit seinem Finger auf die Farbauswahlbuttons wischen kann. Die Farbe, auf der der Finger die Farbauswahl verlässt wird übernommen.

**Comment by Philhil** [comment]
Einstimmig abgelehnt.
