### ISSUE TITLE
Anzeigen der Anleitung beim ersten Start des Spiels

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#30]
Um den Benutzer möglichst schnell abzuholen und die Bedienung auch jedem DAU klar zu machen, wäre mein Vorschlag für die Screens:

- Home

- Einstellungen

- Spiel gestartet

ein Overlay beim ersten Aufruf einzublenden, dass die vorhandenen Eingabefelder und Knöpfe erklärt.
Hier kann uns vielleicht folgende Library helfen: https://github.com/amlcurran/ShowcaseView

**Comment by hphilipp** [comment]
Ist implementiert. Mit Möglichkeit zum Rücksetzen in den Einstellungen, da es jeweils nur beim ersten Anzeigen des Screens kommt.
Passt das so? Soll es eventuell noch in andere Views integriert werden?

**Comment by Philhil** [comment]
Buttons im Kreis deaktivieren, dass die Anleitung zuerst voll durchlaufen werden muss.

**Comment by hphilipp** [comment]
Es kann jetzt nichts mehr außer dem "OK" Button geklickt werden, wenn die Hilfe angezeigt wird.
