### ISSUE TITLE
Button in den Settings um die Highscoreliste zu löschen. Kann auch in der Listenansicht sein.

### ISSUE THREAD

**Issue by hphilipp** [Philhil/DHBW-MasterMind#31]

**Comment by Philhil** [comment]
Add Btns to view: 3dbb392f8cd5da13cf45f67710cbe66b4cb5f867

**Comment by Philhil** [comment]
Should we provide a confirmation before deleting the highscore list? @hphilipp @maexbower @Blackvision

**Comment by maexbower** [comment]
A confirmation dialogue would make sense in my oppinion
