### ISSUE TITLE
Bugs beim laden/speichern

### ISSUE THREAD

**Issue by hphilipp** [Philhil/DHBW-MasterMind#35]
- [x] Bei geladenem Spiel fängt die Zeit von neuem an
- [x] Wenn man geladenes Spiel verlässt, wird immer noch die Spielliste angezeigt
- [x] Wenn geladenes Spiel gewonnen wird, sollte dieses aus der Liste (DB) gelöscht werden

Soll eventuell der Speicherzeitpunkt mit abgespeichert werden?

**Comment by Philhil** [comment]
- [x] Seichern von Farbvorschlag
