### ISSUE TITLE
Änderung der Hintergrundfarbe nicht sofort erkennbar

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#43]
Wenn man es nicht weiß geht der Spieler davon aus, dass das Ändern der Hintergrundfarbe nicht funktioniert hat, bzw. Der Spieler stellt sich unter dem Hintergrund den kompletten Hintergrund vor.

**Comment by hphilipp** [comment]
Im Spiel geht es schon. Muss noch in Colorcode.
