### ISSUE TITLE
Toast Farbe bereits ausgewählt erscheint als Loop wenn man einmal die Einstellungsseite besucht hat

### ISSUE THREAD

**Issue by maexbower** [Philhil/DHBW-MasterMind#44]
Nach einem Update der App (war Hr. R vermutlich auch tun wird) erscheint das Toast Farbe bereits gewählt als endlos Loop. Dieser fehler kommt bei einer neuinstallation nicht und hängt vermutlich mit einer alten Einstellung zusammen.

**Comment by hphilipp** [comment]
Ist angepasst, sollte jetzt ohne Neuinstallation funktionieren.
